### ISSUE TITLE
Authentication problem with shopper token?

### ISSUE THREAD

**Issue by anniebtran** [Giftbit/lightrail-client-ruby#10]
Hello!

I was trying to integrate Lightrail into my Rails app via the Gift Card Drop-in method, and ran into a problem with authentication.

<img width="715" alt="screen shot 2018-01-03 at 3 15 54 pm" src="https://user-images.githubusercontent.com/14334046/34540214-5860c2d4-f099-11e7-90d2-591cab5666ab.png">

I spun up the [sample web app](https://github.com/Giftbit/stripe-integration-sample-webapp) and ran it in Node with the same API keys, and that seems to work without any issues. The reason I think there might be a problem with the `Lightrail::ShopperTokenFactory.generate` function is that I tried copying and pasting the `shoppertoken` generated by the Node app into my Rails app and the widget works perfectly, with no authentication problem. 

Here's the code in my controller:

```   
def new
    # generate shopper token
    if signed_in?
      @shopper_token = Lightrail::ShopperTokenFactory.generate({shopperId: "alice"}, 42300)
    end
end 
```
_*Side note: I tried the above with different `shopperId`s and without the `validity_in_seconds` and it unfortunately didn't solve the problem._ 

And here's the code in my view:
```
<h1>Give a Gift</h1>

<div style="height:100vh;">
    <script
        src="https://embed.lightrail.com/dropin/cardPurchase.js"
        data-shoppertoken="<%= @shopper_token %>"
        >
    </script>
    <!-- The Shopper Token acts as a public api token that is used for issuing the gift card. -->
    <!-- See below for details.  -->
</div>

```

Not sure whether this is an error on my part (which wouldn't be surprising 😆 ) or if there's something going on in the gem, but I would appreciate any help I can get. Thanks!

**Comment by tjukes** [comment]
Hey Annie, thanks for the clear bug report - really helped to get it sorted out quickly (not an error on your part at all). I pushed a fix that should address the issue, so if you update the gem you should be good to go. 
Please let us know if you bump into any further issues. This gem is still in pre-release mode so any testing feedback is very much appreciated.
